# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fbdf6365291689ee57a7d6bbca9734663d6a738d19955a7e74dd6aa4af295353e485adaf812ed45552f4b4c0b56e92a70a22317b908f6efe6bcc09a30a69638

test:
  secret_key_base: 6c3e759859837a6a6a5cd923c18dea512cdac5b880ffb6be353135fafbbaa036e6254cba80ed547e04031cec6d8de89b30c00b2e2b4eee34eeb1252cab88e355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
